channels:
  - conda-forge

dependencies:
  - python=3.8.*
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.5.2
  - cmake=3.25.2
  - qt=5.15.6
  - pip
  - pip:
      - setuptools==65.5.0 # Required to install gym==0.21.0: https://github.com/openai/gym/issues/3176
      - gym3==0.3.3
      - numpy==1.24.2
      - filelock==3.0.10
      - gym==0.21.0
